# version: '3.8'
services:
  axolotl:
    image: winglian/axolotl:main-20240429-py3.10-cu121-2.1.2
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile
    volumes:
      - .:/workspace/axolotl
      - ~/.cache/huggingface/:/root/.cache/huggingface/
    # set environment variables
    environment:
      # Set environment variables
      - GIT_AUTHOR_NAME=Taddeus Buica
      - GIT_AUTHOR_EMAIL=taddeus.buica@sigmance.com
      - GIT_COMMITTER_NAME=Taddeus Buica
      - GIT_COMMITTER_EMAIL=taddeus.buica@sigmance.com
      - WANDB_API_KEY=7784c668498aa24dd48d9611fae335d885ac3df4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    command: tail -f /dev/null
